### ISSUE TITLE
The screen width(from window.innerWidth) shows a horizontal scrollbar, i'm working on that issue.

### ISSUE THREAD

**Issue by steve111MV** [dwmkerr/starfield#5]

**Comment by xharris34** [comment]
in your style within the html section of your code, add " overflow: hidden; " to the code

**Comment by xharris34** [comment]
<head>
<style type="text/css">
	#container {
		height: 100%;
		width:100%;
		overflow: hidden;
		position: absolute;
		left: 0px;
		top: 0px;
		z-index: -10;
	}
</style>
</head>

**Comment by dwmkerr** [comment]
Fixed, thanks @xharris34 and @steve111MV !
